name: 'Datex-tractor'
description: 'Automated issues'
inputs:
  github_token:
    required: true
    description: 'GitHub token'

runs:
  using: 'composite'
  steps:
        
    - name: Setup python...
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
      
    - name: Install requirements...
      shell: bash
      run: |
        python -m venv .venv
        source /tmp/.venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache model...
      id: cache-model
      uses: actions/cache@v4
      with:
        path: /tmp/models
        key: hrms

    - name: Download giant brain blob...
      if: steps.cache-model.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p /tmp/models
        curl -L https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q4_K_M.gguf -o /tmp/models/model.gguf

    - name: Run datex_tractor_script.sh...
      run: |
        source /tmp/.venv/bin/activate
        "${{ github.action_path }}/datex_tractor_script.sh" "hrms"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # Optional, leave empty for default
        MODEL_PATH: /tmp/models/model.gguf
        PROMPT_PATH: ${{ github.action_path }}/prompt.txt
