name: "Datex-tractor"
description: "Automated issues"
inputs:
  github_token:
    required: true
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Run datex_tractor_script.sh
      run: |
        source $HOME/cs/ai/dpsk/dpsk/.venv/bin/activate
        "${{ github.action_path }}/datex_tractor_script.sh"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        MODEL_PATH: /cs/ai/dpsk/dpsk/llama.cpp/models/deepseek-llm-7b-chat.Q4_K_M.gguf
        PROMPT_PATH: /cs/ai/dpsk/dpsk/system.txt

