name: "Datex-tractor"
description: "Automated issues"
inputs:
  github_token:
    required: true
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Run datex_tractor_script.sh
      run: |
        source $HOME/cs/ai/dpsk/dpsk/.venv/bin/activate
        "${{ github.action_path }}/datex_tractor_script.sh"
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        MODEL_PATH: ${{ inputs.model_path }}
        PROMPT_PATH: ${{ inputs.prompt_path }}

