name: 'Datex-tractor'
description: 'Automated issues'
inputs:
  github_token:
    required: true
    description: 'GitHub token'
  use_model:
    required: false
    description: 'Use llm for issue-body generation'
    default: ''
  remove_issue_ids:
    required: false
    description: 'Remove inserted issue ids'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Try to escape infinite loop...
      shell: bash
      run: |
        if [[ "${GITHUB_ACTOR}" == "datextractor[bot]" ]]; then
          echo "Triggered by self, escaping loop..."
          exit 1
        fi
        
    - name: Setup python...
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Cache model...
      if: ${{ inputs.use_model != '' }}
      id: cache-model
      uses: actions/cache@v4
      with:
        path: /tmp/models
        key: hrms

    - name: Download llm...
      if: ${{ inputs.use_model != '' && steps.cache-model.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        mkdir -p /tmp/models
        curl -L https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf -o /tmp/models/model.gguf

    - name: Cache python virtual environment...
      if: ${{ inputs.use_model != '' }}
      id: cache-pip
      uses: actions/cache@v4
      with:
        path: /tmp/venv
        key: venv
     
    - name: Install requirements...
      if: ${{ inputs.use_model != '' && steps.cache-pip.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        python -m venv /tmp/venv
        source /tmp/venv/bin/activate
        pip install --upgrade pip
        pip install -r src/datex_tractor/prompts/requirements.txt

    - name: Run datex_tractor.sh...
      if: ${{ inputs.remove_issue_ids != '' }}
      shell: bash
      run: |
        "${{ github.action_path }}/datex_tractor.sh" "remove" "issue_ids"

    - name: Run datex_tractor.sh...
      shell: bash
      if: ${{ inputs.remove_issue_ids == '' }}
      run: |
        if [[ '${{ inputs.use_model }}' != '' ]]; then
          source /tmp/venv/bin/activate
          "${{ github.action_path }}/datex_tractor.sh" "tiny"
        else
          "${{ github.action_path }}/datex_tractor.sh"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # Optional, leave empty for default
        MODEL_PATH: /tmp/models/model.gguf
        PROMPT_PATH: ${{ github.action_path }}/src/datex_tractor/prompts/tiny.txt
