name: "Datex-tractor"
description: "Automated issues"
inputs:
  github_token:
    required: true
    description: "GitHub token"
  # Optional, leave empty for default
  source_path:
    required: false
    description: "Path to virtual envrionment"
    default: ""
  model:
    required: false
    description: "Either 'dpsk' or 'hrms'"
    default: ""
  model_path:
    required: false
    description: "Path to llm"
    default: ""
  prompt_path:
    required: false
    description: "Path to systemprompt of llm"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run datex_tractor_script.sh
      run: |
        if [[ "${{ inputs.source_path }}" != "" && "${{ inputs.model }}" != "" ]]; then
          source ${{ inputs.source_path }}
          "${{ github.action_path }}/datex_tractor_script.sh" "${{ inputs.model }}"
        else
          "${{ github.action_path }}/datex_tractor_script.sh"
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # Optional, leave empty for default
        MODEL_PATH: ${{ inputs.model_path }}
        PROMPT_PATH: ${{ inputs.prompt_path }}
