name: "Datex-tractor"
description: "Automated issues"
inputs:
  github_token:
    required: true
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Check if is latest version
      run: bash "${{ github.action_path }}/check_latest.sh"

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.13

    - name: Run datex_tractor_script.sh
      run: bash "${{ github.action_path }}/datex_tractor_script.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}

