name: datex-tractor

on:
  push:
    branches:
      - 'v/*'
      - 'dev'

permissions:
  contents: write
  issues: write

jobs:
  Datex-tractor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4

      - name: Check if is latest version
        run: bash .github/todo-extractor/check_latest.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.13
 
      - name: Run datex_tractor_script.sh
        run: bash .github/todo-extractor/datex_tractor_script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
