name: Roll release

on:
  workflow_dispatch:
    branches:
      - "feat/local"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repo...
      uses: actions/checkout@v5

    - name: Release...
      uses: softprops/action-gh-release@v2
      with:
        tag_name: local
        body_path: README.md
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

